[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kucoin-client"
dynamic = ["version"]
classifiers = [
  "Private :: Do Not Upload",
]

[tool.hatch.version]
path = "kucoin.py"
